// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdcvfpqzboomacbxehhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkY3ZmcHF6Ym9vbWFjYnhlaGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njc0NjUsImV4cCI6MjA2MjA0MzQ2NX0.VK4wwZmSif4BDTmsuCamJiXYJ_Yrjyu4fj9NA40OHcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);